name: Pipeline CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit
    - name: Run test
      run: pytest -v test_app.py
    - name: Run bandit
      run: |
        bandit app.py -f html -o bandit-report.html --quiet
        bandit app.py
      continue-on-error: true
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.html
  owasp-zap:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: nohup python3 app.py &
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:5000'
          artifact_name: zap-report.html
          allow_issue_writing: false
      - name: Download Bandit Report
        uses: actions/download-artifact@v4
        with:
          name: bandit-report
      - name: Send ZAP and Bandit Report to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ls
          curl -X POST -H "Content-Type: multipart/form-data" \
            -F "content=Novo relatório OWASP ZAP!" \
            -F "file=@zap-report.html" \
            -F "file=@bandit-report.html" \
            "$DISCORD_WEBHOOK"


  # semgrep:
  #   name: Semgrep CI
  #   runs-on: ubuntu-latest
  #   container:
  #     image: semgrep/semgrep
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Run Semgrep
  #       run: semgrep ci
  #       env:
  #         SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  #   if: "github.actor != 'dependabot[bot]'"
  # safety:
  #   runs-on: ubuntu-latest
  #   name: Safety CI
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pyupio/safety-action@v1
  #       with:
  #         api-key: ${{ secrets.SAFETY_API_KEY }}