name: Pipeline CI/CD

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit
    - name: Run test
      run: pytest -v test_app.py
    - name: Run bandit
      run: |
        bandit app.py
        bandit app.py -f html -o bandit-report.html --quiet
      continue-on-error: true
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.html
    
  # semgrep:
  #   name: Semgrep CI
  #   runs-on: ubuntu-latest
  #   container:
  #     image: semgrep/semgrep
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Run Semgrep
  #       run: semgrep ci
  #       env:
  #         SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  #   if: "github.actor != 'dependabot[bot]'"
  # safety:
  #   runs-on: ubuntu-latest
  #   name: Safety CI
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pyupio/safety-action@v1
  #       with:
  #         api-key: ${{ secrets.SAFETY_API_KEY }}
