name: Pipeline CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run test
      run: pytest -v test_app.py
  semgrep:
     name: semgrep/ci
     runs-on: ubuntu-latest 