name: Pipeline CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run test
      run: pytest -v test_app.py
  semgrep:
    name: Semgrep CI
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    if: "github.actor != 'dependabot[bot]'"
  safety:
    runs-on: ubuntu-latest
    name: Safety CI
    steps:
      - uses: actions/checkout@v4
      - uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
  security-dast:
    name: Owasp Zap Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run app
        run: python3 app.py
      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://0.0.0.0'
      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
